---
title: "Tarea 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preparativos carga de paquetes 

```{r carga librerias, message = FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
```

## Carga de datos

```{r carga-datos}

# Carga de datos de rios desde un archivo CSV 
rios <-
  read.csv(file = 'https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/hidrologia/fdc/fdc.csv')

# Carga de datos de covid-19 desde un archivo CSV
covid <- 
  read.csv(
    file='https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/minsalud/covid/ultimafecha_CSV_GENERAL.csv', 
    sep = ","
  )

```

## (40%) Gráfico de barras apiladas que muestre el caudal de los ríos Pandora y Bananito por cada uno de los 12 meses del año.

### Organizacion de datos
```{r organizacion-datos-rios}
# Cambio de nombre de las columnas mediante rename()
rios <-
  rios %>%
  rename(fecha = Tiempo,
         pandora = Pandora.mm..637km2.,
         banano = Banano.mm..90km2.)

# Conversión de una columna a tipo Date y creación de una nueva columna. Calculo de promedios de caudales
cauda_sum<-
  rios %>%
  pivot_longer(cols = c(`banano`, `pandora`), names_to = "rio", values_to   = "caudales") %>%
  mutate(fecha = as.Date(fecha, format = "%m/%d/%Y"))%>%
  group_by(rio, mes = format(fecha,"%m")) %>%
  summarise(caudales = sum(caudales))

```

### Graficacion
```{r graficacion-rios}

# Gráfico de barras apiladas
ggplot(cauda_sum, aes(x = mes, y = caudales, fill = rio)) +
  geom_col() +
  ggtitle("Caudal de los ríos Pandora y Bananito") +
  xlab("Meses") +
  ylab("Caudal")+
  labs(fill="Rio")
  
```

## (20%) Histograma que muestre la distribución de los casos nuevos de covid en Costa Rica. Elija cuidadosamente el tamaño de los “bins”.

### Organizacion de datos
```{r organizacion-datos-covid}
covid_posi <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, nuevos_positivos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))
```


### Graficacion
```{r graficacion-histograma}
#Histograma con opciones
covid_posi %>%
  ggplot(aes(x = nuevos_positivos)) +
  geom_histogram(binwidth = 50,
                 color = "blue",
                 fill = 'white') +
  ggtitle("Histograma Casos Nuevos") +    
  xlab("Cantidad")+
  ylab("Frecuencia Casos")

```






